apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: risk
      username: $__env{CLICKHOUSE_USER}
    secureJsonData:
      password: $__env{CLICKHOUSE_PASSWORD}
    editable: true
